blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/yacchi/go-jsonrpc-client/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/yacchi/go-jsonrpc-client/tree/main/docs
    about: Check the documentation for usage information.
