name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x', '1.23.x', '1.22.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Format check
      run: |
        make format
        if [ -n "$(git diff)" ]; then
          echo "Code is not formatted. Please run 'make format' locally."
          exit 1
        fi

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Test with coverage
      run: make test-coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out
        if-no-files-found: ignore
